/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package veteri_feliz;

import Veteri_Feliz.ArchivoPlano;
import Veteri_Feliz.ArchivoPlanoVet;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanj
 */
public class FrmVeterinario extends javax.swing.JFrame {

    ArrayList<Veterinario> ListaVeterinario;
    
    public FrmVeterinario() {
        initComponents();
        ListaVeterinario = new ArrayList<>();
        getContentPane().setBackground(new Color(255, 202, 156));
        jButton_Cargar1ActionPerformed(null); // Recargar la tabla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_IDVeterinario = new javax.swing.JTextField();
        jTextField_CedulaVeterinario = new javax.swing.JTextField();
        jTextField_NombreVeterinario = new javax.swing.JTextField();
        jButton_Guardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Vet = new javax.swing.JTable();
        jButton_Cargar1 = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jButton_Editar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel1.setText("Datos Veterinario");

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel3.setText("Cedula:");

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel4.setText("Nombre:");

        jTextField_IDVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDVeterinarioActionPerformed(evt);
            }
        });

        jButton_Guardar.setText("Guardar");
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });

        jTable_Vet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Cedula", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Vet);

        jButton_Cargar1.setText("Cargar");
        jButton_Cargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cargar1ActionPerformed(evt);
            }
        });

        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });

        jButton_Editar.setText("Editar");
        jButton_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_CedulaVeterinario, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_NombreVeterinario, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_IDVeterinario, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(16, 16, 16))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton_Cargar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_IDVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_CedulaVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_NombreVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Guardar)
                    .addComponent(jButton_Cargar1)
                    .addComponent(jButton_Eliminar)
                    .addComponent(jButton_Editar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_IDVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDVeterinarioActionPerformed

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        Veterinario vet =new Veterinario();
        
        // Validación de campos vacíos en una sola línea
        if (jTextField_NombreVeterinario.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            vet.Id_Veterinario = Integer.parseInt(jTextField_IDVeterinario.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Formato Incorrecto en el ID", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            vet.Cedula_Veterinario = Integer.parseInt(jTextField_CedulaVeterinario.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Formato Incorrecto en la Cedula", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        vet.Id_Veterinario = Integer.parseInt(jTextField_IDVeterinario.getText().trim());
        vet.Cedula_Veterinario = Integer.parseInt(jTextField_CedulaVeterinario.getText().trim());
        vet.Nombre_Veterinario = jTextField_NombreVeterinario.getText().trim();
        
        // Mensaje de éxito
        JOptionPane.showMessageDialog(null, "Datos capturados correctamente:\nID: " + vet.Id_Veterinario + "\nCedula: " + vet.Cedula_Veterinario +
        "\nNombre: " + vet.Nombre_Veterinario,"Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        vet.setId_Veterinario(vet.Id_Veterinario);
        vet.setCedula_Veterinario(vet.Cedula_Veterinario);
        vet.setNombre_Veterinario(vet.Nombre_Veterinario);
        ListaVeterinario.add(vet);
        ArchivoPlanoVet.guardarEnArchivo(ListaVeterinario);
        jButton_Cargar1ActionPerformed(null); // Recargar la tabla
    }//GEN-LAST:event_jButton_GuardarActionPerformed

    private void jButton_Cargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cargar1ActionPerformed
        // Cargar los estudiantes desde el archivo y agregamos a la lista
        List<Veterinario> veterinarioCargado = ArchivoPlanoVet.cargarDesdeArchivo();

        //Limpiar la tabla y la lista actual para luego cargar los datos
        ListaVeterinario.clear();
        DefaultTableModel modelo = (DefaultTableModel) jTable_Vet.getModel();
        modelo.setRowCount(0);  // Limpiar las filas de la tabla

        // Agregar los estudiantes cargados a la lista y a oa tabla
        for (Veterinario veterinario : veterinarioCargado) {
            ListaVeterinario.add(veterinario);
            modelo.addRow(new Object[] {veterinario.getId_Veterinario(), veterinario.getCedula_Veterinario(), veterinario.getNombre_Veterinario()});
        }
    }//GEN-LAST:event_jButton_Cargar1ActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        // Validar que el campo no esté vacío
    if (jTextField_IDVeterinario.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor escribe una cédula para eliminar.");
        return;
    }

    try {
        int IdAEliminar = Integer.parseInt(jTextField_IDVeterinario.getText().trim());
        ArchivoPlanoVet.eliminarDeArchivo(IdAEliminar);
        jButton_Cargar1ActionPerformed(null); // Recargar la tabla después de eliminar
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "La cédula debe ser un número válido.");
    }
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jButton_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditarActionPerformed
        if (jTextField_IDVeterinario.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor escribe un ID.");
        return;
    }

    try {
        int Id = Integer.parseInt(jTextField_IDVeterinario.getText().trim());
        int nuevaCedula = Integer.parseInt(jTextField_CedulaVeterinario.getText().trim());
        String nuevoNombre = jTextField_NombreVeterinario.getText().trim();

        ArchivoPlanoVet.modificarEnArchivo(Id, nuevaCedula, nuevoNombre);
        jButton_Cargar1ActionPerformed(null); // Recargar la tabla

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "La cédula debe ser un número válido.");
    }
    }//GEN-LAST:event_jButton_EditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVeterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cargar1;
    private javax.swing.JButton jButton_Editar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Vet;
    private javax.swing.JTextField jTextField_CedulaVeterinario;
    private javax.swing.JTextField jTextField_IDVeterinario;
    private javax.swing.JTextField jTextField_NombreVeterinario;
    // End of variables declaration//GEN-END:variables
}
