/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package veteri_feliz;

/**
 *
 * @author juanj
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MainMenu = new javax.swing.JMenuBar();
        jMenu_MainMenu = new javax.swing.JMenu();
        jMenu_Persona = new javax.swing.JMenu();
        jMenu_Mascota = new javax.swing.JMenu();
        jMenu_Veterinario = new javax.swing.JMenu();
        jMenu_Cita = new javax.swing.JMenu();
        jMenu_Vacunas = new javax.swing.JMenu();
        jMenu_Historia = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\juanj\\Downloads\\Veteri_Feliz\\Imgs\\Vete (1) (1).jpg")); // NOI18N

        jMenu_MainMenu.setText("Menú");
        jMenu_MainMenu.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jMenu_MainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_MainMenuMouseClicked(evt);
            }
        });
        MainMenu.add(jMenu_MainMenu);

        jMenu_Persona.setText("Persona");
        jMenu_Persona.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jMenu_Persona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_PersonaMouseClicked(evt);
            }
        });
        MainMenu.add(jMenu_Persona);

        jMenu_Mascota.setText("Mascota");
        jMenu_Mascota.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jMenu_Mascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_MascotaMouseClicked(evt);
            }
        });
        MainMenu.add(jMenu_Mascota);

        jMenu_Veterinario.setText("Veterinario");
        jMenu_Veterinario.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jMenu_Veterinario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_VeterinarioMouseClicked(evt);
            }
        });
        MainMenu.add(jMenu_Veterinario);

        jMenu_Cita.setText("Cita");
        jMenu_Cita.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jMenu_Cita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_CitaMouseClicked(evt);
            }
        });
        MainMenu.add(jMenu_Cita);

        jMenu_Vacunas.setText("Vacunas");
        jMenu_Vacunas.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jMenu_Vacunas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_VacunasMouseClicked(evt);
            }
        });
        MainMenu.add(jMenu_Vacunas);

        jMenu_Historia.setText("Historia");
        jMenu_Historia.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jMenu_Historia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_HistoriaMouseClicked(evt);
            }
        });
        MainMenu.add(jMenu_Historia);

        setJMenuBar(MainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_MainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_MainMenuMouseClicked
        //Vacío
    }//GEN-LAST:event_jMenu_MainMenuMouseClicked

    private void jMenu_PersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_PersonaMouseClicked
    PersonaGUI personagui = new PersonaGUI(); // Crear una instancia del formulario
    personagui.setVisible(true); // Mostrar el nuevo formulario
    personagui.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Cierra solo esta ventana al salir
    }//GEN-LAST:event_jMenu_PersonaMouseClicked

    private void jMenu_MascotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_MascotaMouseClicked
    FrmMascota frmmascota = new FrmMascota(); // Crear una instancia del formulario
    frmmascota.setVisible(true); // Mostrar el nuevo formulario
    frmmascota.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Cierra solo esta ventana al salir
    }//GEN-LAST:event_jMenu_MascotaMouseClicked

    private void jMenu_VeterinarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_VeterinarioMouseClicked
    FrmVeterinario frmveterinario = new FrmVeterinario(); // Crear una instancia del formulario
    frmveterinario.setVisible(true); // Mostrar el nuevo formulario
    frmveterinario.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Cierra solo esta ventana al salir
    }//GEN-LAST:event_jMenu_VeterinarioMouseClicked

    private void jMenu_CitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_CitaMouseClicked
    FrmCita frmcita = new FrmCita(); // Crear una instancia del formulario
    frmcita.setVisible(true); // Mostrar el nuevo formulario
    frmcita.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Cierra solo esta ventana al salir
    }//GEN-LAST:event_jMenu_CitaMouseClicked

    private void jMenu_VacunasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_VacunasMouseClicked
    FrmHistorial_Vacunas frmvacunas = new FrmHistorial_Vacunas(); // Crear una instancia del formulario
    frmvacunas.setVisible(true); // Mostrar el nuevo formulario
    frmvacunas.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Cierra solo esta ventana al salir
    }//GEN-LAST:event_jMenu_VacunasMouseClicked

    private void jMenu_HistoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_HistoriaMouseClicked
    FrmHistoria_Clinica frmhistoria_clinica = new FrmHistoria_Clinica(); // Crear una instancia del formulario
    frmhistoria_clinica.setVisible(true); // Mostrar el nuevo formulario
    frmhistoria_clinica.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Cierra solo esta ventana al salir
    }//GEN-LAST:event_jMenu_HistoriaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MainMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu_Cita;
    private javax.swing.JMenu jMenu_Historia;
    private javax.swing.JMenu jMenu_MainMenu;
    private javax.swing.JMenu jMenu_Mascota;
    private javax.swing.JMenu jMenu_Persona;
    private javax.swing.JMenu jMenu_Vacunas;
    private javax.swing.JMenu jMenu_Veterinario;
    // End of variables declaration//GEN-END:variables
}
